# Folders containing the un-processed forcings for a domain in mhm

# Archivo vectorial del dominio
roi_file: ../DATA/SHP/11342001.geojson

# Coordenadas de las estaciones fluviometricas.
fluv_station_file: ../DATA/SHP/est_fluv/gauge_station_coords.geojson

# Caudales observados en m3s y mm
streamflow_data_file: ../DATA/SHP/Cuencas_CAMELS/CAMELS_CL_v202201/q_m3s_day.csv
streamflow_data_file_mm: ../DATA/SHP/Cuencas_CAMELS/CAMELS_CL_v202201/q_mm_day.csv

# DEM SRTM 30m
dem_file: ../DATA/RAST/Topography/DEM/SRTM_DEM_Chile_uncompressed.tif

# Land Cover Zhao
land_cover_file: ../DATA/RAST/Land Cover/LCZhao/LC_CHILE_2014_b.tif

# Leaf area index (LAI)
lai_file: ../DATA/RAST/LAI/MODIS_LTM_LAI_Chile_uncompressed.tif

# Mapa geologico. Mapa geologico de chile en formato vectorial o raster GLIM (opcion global)
geo_file: ../DATA/SHP/Geologia/Geologia_completo.geojson
geo_file_global: ../DATA/RAST/Geology/glim_wgs84_0point5deg.txt.asc

# Mapa de suelo (1 archivo por horizonte y variable (Bulkd, Clay y Sand)
# y profundidades estandarizadas (0-5, 5-15, 15-30, 30-60, 60-100)
soil_folder: ../DATA/RAST/Soil/SoilMaps_MEAN

# Forzantes climaticas del modelo
variables_clim:
  pr:
    input_dir: ../DATA/RAST/Clim/Pr/day024
  tmin:
    input_dir: ../DATA/RAST/Clim/tmin_tmax/v2.5_best_day
  tmax:
    input_dir: ../DATA/RAST/Clim/tmin_tmax/v2.5_best_day
  tmean:
    input_dir: ../DATA/RAST/Clim/tmean/v2.5_best_day
  et0:
    input_dir: ../DATA/RAST/Clim/et0/v2.5_best_day
    
# Red hidrologica de chile (unused)
hydro_network_file: ../DATA/SHP/red_hidro/Red_Hidrografica_Final.shp

# De aqui en adelante los folders corresponden al nombre de la carpeta donde se
#   guardaran los archivos procesados
out_folder: ./OUT
exe_folder: ./EXE
opt_folder: ./OPT_DATA
header_folder: ./headers
latlon_folder: ./latlon
morph_folder: ./morph
meteo_folder: ./meteo
lai_folder: ./lai
lc_folder: ./landcover
gauge_folder: ./gauges

# carpeta donde se encuentra el archivo create_latlon.py (parte de la instalacion de mhm)
latlon_script_folder: /Users/mhm/Desktop/FONDECYT_CAMILA/mhm_work/installation/mhm/pre-proc

# CONFIGURACIONES

# Codigo EPSG usado para configuracion
latlon_crs: 4326

# Tamaño de la celda (debe coincidir con archivo mhm.nml)
cellsize: 0.001953125 #
cellsize_clim: 0.03125

# Periodo de tiempo a simular.
start_date: '1960-01-01'
end_date: '2021-12-31'

# Calibrar modelo?
calibrate_model: true
