dem_file: ../DATA/RAST/Topography/DEM/SRTM_DEM_Chile_uncompressed.tif
land_cover_file: ../DATA/RAST/Land Cover/LCZhao/LC_CHILE_2014_b.tif
lai_file: ../DATA/RAST/LAI/MODIS_LTM_LAI_Chile_uncompressed.tif
geo_file: ../DATA/SHP/Geologia/Geologia_completo.geojson
geo_file_global: ../DATA/RAST/Geology/glim_wgs84_0point5deg.txt.asc
soil_folder: ../DATA/RAST/Soil/SoilMaps_MEAN
roi_file: ../DATA/SHP/Cuencas_BNA/zonification_mergecamels/zone_1.geojson
hydro_network_file: ../DATA/SHP/red_hidro/Red_Hidrografica_Final.shp
fluv_station_file: ../DATA/TABLE/est_fluv/catchment_gauge_coords.csv
streamflow_data_file: ../DATA/SHP/Cuencas/CAMELS_CL_v202201/q_m3s_day.csv
streamflow_data_file_mm: ../DATA/SHP/Cuencas/CAMELS_CL_v202201/q_mm_day.csv
variables_clim:
  pr:
    input_dir: ../DATA/RAST/Clim/Pr/day024
  tmin:
    input_dir: ../DATA/RAST/Clim/tmin_tmax/v2.5_best_day
  tmax:
    input_dir: ../DATA/RAST/Clim/tmin_tmax/v2.5_best_day
  tmean:
    input_dir: ../DATA/RAST/Clim/tmean/v2.5_best_day
  et0:
    input_dir: ../DATA/RAST/Clim/et0/v2.5_best_day
out_folder: ./OUT
exe_folder: ./EXE
opt_folder: ./OPT_DATA
header_folder: ./headers
latlon_script_folder: /Users/mhm/Desktop/FONDECYT_CAMILA/mhm_work/installation/mhm/pre-proc
latlon_folder: ./latlon
morph_folder: ./morph
meteo_folder: ./meteo
lai_folder: ./lai
lc_folder: ./landcover
gauge_folder: ./gauges
latlon_crs: 4326
cellsize: 0.001953125
start_date: '1960-01-01'
end_date: '2021-12-31'
cellsize_clim: 0.03125
calibrate_model: true
